development:
  :address: smtp.gmail.com
  :port: 587
  :domain: gmail.com
  :authentication: plain
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :domain: gmail.com
  :authentication: plain
  :enable_starttls_auto: true
